#!/usr/bin/env bash
#
# Regenerates machine-state.md with current system information.
# Run manually or via package manager hooks.
#

set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# Detect OS and set output path
detect_os() {
    case "$(uname -s)" in
        Linux)
            if [[ -f /etc/arch-release ]]; then
                echo "arch"
            elif [[ -f /etc/debian_version ]]; then
                echo "debian"
            elif [[ -f /etc/fedora-release ]]; then
                echo "fedora"
            elif [[ -f /etc/alpine-release ]]; then
                echo "alpine"
            else
                echo "linux"
            fi
            ;;
        Darwin)
            echo "darwin"
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

OS="$(detect_os)"

# Set output path based on OS
case "$OS" in
    arch)
        OUTPUT_FILE="$DOTFILES_DIR/linux/arch/ai-context/machine-state.md"
        ;;
    debian)
        OUTPUT_FILE="$DOTFILES_DIR/linux/debian/ai-context/machine-state.md"
        ;;
    fedora)
        OUTPUT_FILE="$DOTFILES_DIR/linux/fedora/ai-context/machine-state.md"
        ;;
    alpine)
        OUTPUT_FILE="$DOTFILES_DIR/linux/alpine/ai-context/machine-state.md"
        ;;
    darwin)
        OUTPUT_FILE="$DOTFILES_DIR/darwin/ai-context/machine-state.md"
        ;;
    *)
        OUTPUT_FILE="$DOTFILES_DIR/common/ai-context/machine-state.md"
        ;;
esac

# Ensure directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Helper: get version if command exists
version_of() {
    local cmd="$1"
    shift
    if command -v "$cmd" &>/dev/null; then
        if [[ $# -gt 0 ]]; then
            "$cmd" "$@" 2>/dev/null | head -n1
        else
            "$cmd" --version 2>/dev/null | head -n1
        fi
    else
        echo "not installed"
    fi
}

# Helper: get package count
package_count() {
    case "$OS" in
        arch)
            pacman -Q 2>/dev/null | wc -l
            ;;
        debian)
            dpkg -l 2>/dev/null | grep -c '^ii'
            ;;
        darwin)
            brew list --formula 2>/dev/null | wc -l | tr -d ' '
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

# Helper: get recently installed packages (last 10)
recent_packages() {
    case "$OS" in
        arch)
            grep -E '\[ALPM\] installed' /var/log/pacman.log 2>/dev/null | tail -10 | awk '{print $4}' | sed 's/(.*//'
            ;;
        debian)
            grep ' install ' /var/log/dpkg.log 2>/dev/null | tail -10 | awk '{print $4}' | cut -d: -f1
            ;;
        darwin)
            # Homebrew doesn't have a great install log, just list some recent
            brew list --formula -1 2>/dev/null | tail -10
            ;;
        *)
            echo "unavailable"
            ;;
    esac
}

# Generate the file
cat > "$OUTPUT_FILE" << EOF
# Machine State

> Auto-generated by \`refresh-machine-state.sh\`
> Last updated: $(date -Iseconds)

## System

- **OS**: $(uname -s) $(uname -r)
- **Hostname**: $(hostname)
- **Architecture**: $(uname -m)

## Shell

- **Current shell**: $SHELL
- **Bash**: $(version_of bash)
- **Zsh**: $(version_of zsh)

## Languages

| Language | Version |
|----------|---------|
| Rust | $(version_of rustc) |
| Python | $(version_of python3) |
| Node | $(version_of node -v) |
| Go | $(version_of go version) |

## Tools

| Tool | Version |
|------|---------|
| Git | $(version_of git) |
| Docker | $(version_of docker -v) |
| kubectl | $(version_of kubectl version --client --short 2>/dev/null || version_of kubectl version --client) |
| Terraform | $(version_of terraform -v) |
| Neovim | $(version_of nvim) |

## Packages

- **Total installed**: $(package_count)
- **Package manager**: $(case "$OS" in arch) echo "pacman";; debian) echo "apt";; darwin) echo "homebrew";; *) echo "unknown";; esac)

### Recently Installed

\`\`\`
$(recent_packages)
\`\`\`
EOF

echo "Updated: $OUTPUT_FILE"
